apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment2 # Name of deployment
  labels:
    app: k8s-app
spec:
  replicas: 1      # Number of pods
  selector:        # Pod selector for deployment
    matchLabels:
      app:  k8s-app2
  template:
    metadata:
      labels:
        app:  k8s-app2
    spec:
      containers:
      - name: spring-boot-k8s-app2 
        imagePullPolicy: IfNotPresent
        image: spring-boot-k8s-app2:1.0.0   #image name
        ports:
        - containerPort: 8081

        
        